---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/racefinance.site/
    - /bin/rsync -av --exclude='.git*' --exclude='.env*' --exclude='data/' --exclude='public/uploads/' --exclude='backups/' ./ $DEPLOYPATH
